🐛 Fix DatabaseQuerySafe compilation error in Reservation_Confirmed.aspx.cs
Issue:
- Line 144 was calling code.DatabaseQuerySafe() where 'code' is of type _Default
- _Default class does not have DatabaseQuerySafe method

Fix:
- Changed to code2.DatabaseQuerySafe() where 'code2' is of type 'code' class
- The 'code' class contains the DatabaseQuerySafe method with parameterized query support

This fixes the compilation error:
'_Default' does not contain a definition for 'DatabaseQuerySafe'